name = "addertrace"
version = "0.1.0"
defaultTargets = ["AdderTrace", "SupplementAdder"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "f897ebcf72cd16f89ab4577d0c826cd14afaafc7"

[[lean_lib]]
name = "AdderTrace"

[[lean_lib]]
name = "SupplementAdder"
